name: golangci-lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        # the default behavior of checkout is to merge master into the PR branch,
        # this forces checkout to run the actual HEAD
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
        with:
          skip-cache: true
